# Generated by Django 5.0.4 on 2024-05-31 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(choices=[('Banteay Meanchey', 'Banteay Meanchey'), ('Battambang', 'Battambang'), ('Kampong Cham', 'Kampong Cham'), ('Kampong Chhnang', 'Kampong Chhnang'), ('Kampong Speu', 'Kampong Speu'), ('Kampong Thom', 'Kampong Thom'), ('Kampot', 'Kampot'), ('Kandal', 'Kandal'), ('Koh Kong', 'Koh Kong'), ('Kratie', 'Kratie'), ('Mondulkiri', 'Mondulkiri'), ('Phnom Penh', 'Phnom Penh'), ('Preah Vihear', 'Preah Vihear'), ('Prey Veng', 'Prey Veng'), ('Pursat', 'Pursat'), ('Ratanakiri', 'Ratanakiri'), ('Siem Reap', 'Siem Reap'), ('Preah Sihanouk', 'Preah Sihanouk'), ('Stung Treng', 'Stung Treng'), ('Svay Rieng', 'Svay Rieng'), ('Takeo', 'Takeo'), ('Oddar Meanchey', 'Oddar Meanchey'), ('Kep', 'Kep'), ('Pailin', 'Pailin'), ('Tboung Khmum', 'Tboung Khmum')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
