# Generated by Django 5.0.4 on 2024-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
